### ISSUE TITLE
can this code be used for motor imagery?

### ISSUE THREAD

**Issue by wuguowei1994** [pouya-bashivan/EEGLearn#17]
can this code be used for motor imagery?

**Comment by brylie** [comment]
@wuhualu185086661 most likely, yes. What electrode placement are you using to record your data? Please describe more the experimental conditions when you collected the data.

**Comment by brylie** [comment]
Some examples from other research:

- [motor imagery and object-oriented motor imagery may contra-laterally suppress mu and beta rhythms](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0144256)
- [Comparison of EEG-Features and Classification Methods for Motor Imagery in Patients with Disorders of Consciousness](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0080479)
- [Evaluation of EEG Oscillatory Patterns and Cognitive Process during Simple and Compound Limb Motor Imagery](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0114853)
- [Translation of EEG Spatial Filters from Resting to Motor Imagery Using Independent Component Analysis](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0037665)
- [Classification of Four-Class Motor Imagery Employing Single-Channel Electroencephalography](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0098019)
- [Motor imagery decoding from EEG data using the Common Spatial Pattern (CSP)](http://martinos.org/mne/stable/auto_examples/decoding/plot_decoding_csp_eeg.html)

Relatedly, 
- [Improving the Performance of an EEG-Based Motor Imagery Brain Computer Interface Using Task Evoked Changes in Pupil Diameter](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0121262)
- [The Importance of Visual Feedback Design in BCIs; from Embodiment to Motor Imagery Learning](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0161945)

**Comment by brylie** [comment]
There is a **related topic on NeuroBB**: [How to classify motor imagery from EEG data](https://neurobb.com/t/how-to-classify-motor-imagery-from-eeg-data/555/1)

**Comment by wuhualu185086661** [comment]
thank you very much.
when i use this code in python2,a problem came out:
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import eeglearn.eeg_cnn_lib as eeglib
  File "/home/steven/gitDownloads/EEGLearn/eeglearn/eeg_cnn_lib.py", line 17, in <module>
    import lasagne
  File "/usr/local/lib/python2.7/dist-packages/lasagne/__init__.py", line 19, in <module>
    from . import layers
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name downsample
I hava installed all things needed,why does this problem came out?

**Comment by brylie** [comment]
As an aside, please consider using Python 3 when possible.

Are you working in a virtual environment? Can you go into a Python prompt and type `import ...` for each of those dependencies?
